### ISSUE TITLE
Use from source

### ISSUE THREAD

**Issue by Tigzy** [evilsocket/ergo-pe-av#1]
Hello, 
I don't see any setup.py in the repo, how can I use the project directly by calling the python scripts ? Where's the ergo entrypoint ?
Thanks,

**Comment by Tigzy** [comment]
I've installed the requirements (ergo, lief) but there's no ergo binary deployed. Should I install it with apt install ergo as well ?

**Comment by Tigzy** [comment]
Ok so I've installed ergo from source and the message is different now. 

![image](https://user-images.githubusercontent.com/9531438/58410856-55c3cb00-8073-11e9-8578-238953319cf1.png)

**Comment by evilsocket** [comment]
i have no idea what you did there ... just uninstall everything, then:

    sudo pip3 install ergo-ai

that's all you need

**Comment by Tigzy** [comment]
This is what I've started to do, and why I came with this error.

**Comment by Tigzy** [comment]
Let me try on another machine, but there's definitely a need for documentation on the install of ergo here. ergo-ai isn't mentioned in this project's README :)

**Comment by evilsocket** [comment]
it's explicitly stated (and linked) that ergo is a dependency, and here's all the instructions you should have followed https://github.com/evilsocket/ergo#installing ...

**Comment by evilsocket** [comment]
the requirements.txt was wrong tho (ergo instead of ergo-ai), i just fixed it

**Comment by evilsocket** [comment]
fixed with https://github.com/evilsocket/ergo/commit/c7e2af1120b3db9fb02750b5d43b3a6e2fbe145a

**Comment by Tigzy** [comment]
Thanks, I think I was mislead by the wrong ergo package in requirements, after removing the source-built package and reinstalled with pip3 is worked as expected. Thanks for this awesome project :)

**Comment by evilsocket** [comment]
glad we finally made it!
