### ISSUE TITLE
Negative relevance ?

### ISSUE THREAD

**Issue by Tigzy** [evilsocket/ergo-pe-av#5]
Hello, 
I'm playing with the ergo relevance command, and I'm wondering what the value means. 
I'm guessing the higher the percentage the better the feature, but what does negative value mean ? Does positive mean more likely to be a clean sample and negative a malware (or the opposite, depending on labels order) ? 

![image](https://user-images.githubusercontent.com/9531438/59204784-a540e580-8ba1-11e9-821e-c22e0076b20c.png)

**Comment by evilsocket** [comment]
no, a positive relevance means that that feature increases the overall accuracy if used, a negative one instead (marked in red), means it decreases the accuracy and should be removed ... not sure what dataset you're using tho

**Comment by Tigzy** [comment]
Thanks for explanation. The dataset is the one from pe-av
